"""Public admin/observer/break-glass client distribution.

Thin role surfaces over shared ``_workhold_client_core`` primitives.
Observer operations: getCapabilities, getTask, listTaskAttempts, getQueue,
getStats, getMaintenanceStatus, listInspectionTasks, listInspectionAttempts,
listDeadLetters (see ``packages/client-operation-ownership.json``).
Admin audit/maintenance: listAdminAudit, getMaintenanceStatus, runMaintenance.
Admin recovery: replayDeadLetter, preview/execute bulk replay/cancel.
"""

from __future__ import annotations

from _workhold_client_core.capabilities import Capabilities
from _workhold_client_core.errors import (
    AuthenticationError,
    MalformedResponseError,
    ProtocolError,
    QueueClientError,
    TimeoutError,
    TransportError,
)
from _workhold_client_core.models import Task, TaskState
from _workhold_client_core.transport import HttpJsonTransport, encode_path_segment
from workhold_admin.admin import AdminClient
from workhold_admin.break_glass import BreakGlassClient
from workhold_admin.models import (
    AdminMutationResult,
    AuditOperation,
    AuditPage,
    AuditRecord,
    Attempt,
    AttemptOutcome,
    AttemptPage,
    BackoffStrategy,
    BULK_BATCH_MAX,
    BULK_CANDIDATE_MAX,
    BreakGlassCounterResult,
    BreakGlassMutationResult,
    BreakGlassReplayLimitResult,
    BulkExecuteResult,
    BulkItemOutcome,
    BulkItemOutcomeKind,
    BulkOperation,
    BulkPreviewResult,
    CONFIRMATION_TOKEN_MAX_LENGTH,
    ConfigVersion,
    CURSOR_MAX_LENGTH,
    DeadLetterPage,
    DeadLetterReplayResult,
    IDEMPOTENCY_KEY_MAX_LENGTH,
    IDEMPOTENCY_KEY_MIN_LENGTH,
    MaintenanceOutcome,
    MaintenanceRunResult,
    MaintenanceStatus,
    PAGE_LIMIT_DEFAULT,
    PAGE_LIMIT_MAX,
    PAGE_LIMIT_MIN,
    PolicyVersion,
    Queue,
    QueuePage,
    QueueState,
    REASON_MAX_LENGTH,
    RetryPolicy,
    RetryPolicyDraft,
    StatsAvailability,
    StatsFreshness,
    StatsMaintenanceSummary,
    StatsQueueAggregate,
    StatsSnapshot,
    StatsTelemetrySource,
    StatsTelemetrySummary,
    TaskPage,
)
from workhold_admin.observer import ObserverClient

__version__ = "1.0.4"  # x-release-please-version

__all__ = [
    "AdminClient",
    "AdminMutationResult",
    "AuditOperation",
    "AuditPage",
    "AuditRecord",
    "Attempt",
    "AttemptOutcome",
    "AttemptPage",
    "AuthenticationError",
    "BackoffStrategy",
    "BULK_BATCH_MAX",
    "BULK_CANDIDATE_MAX",
    "BreakGlassClient",
    "BreakGlassCounterResult",
    "BreakGlassMutationResult",
    "BreakGlassReplayLimitResult",
    "BulkExecuteResult",
    "BulkItemOutcome",
    "BulkItemOutcomeKind",
    "BulkOperation",
    "BulkPreviewResult",
    "Capabilities",
    "CONFIRMATION_TOKEN_MAX_LENGTH",
    "ConfigVersion",
    "CURSOR_MAX_LENGTH",
    "DeadLetterPage",
    "DeadLetterReplayResult",
    "HttpJsonTransport",
    "IDEMPOTENCY_KEY_MAX_LENGTH",
    "IDEMPOTENCY_KEY_MIN_LENGTH",
    "MaintenanceOutcome",
    "MaintenanceRunResult",
    "MaintenanceStatus",
    "MalformedResponseError",
    "ObserverClient",
    "PAGE_LIMIT_DEFAULT",
    "PAGE_LIMIT_MAX",
    "PAGE_LIMIT_MIN",
    "PolicyVersion",
    "ProtocolError",
    "Queue",
    "QueueClientError",
    "QueuePage",
    "QueueState",
    "REASON_MAX_LENGTH",
    "RetryPolicy",
    "RetryPolicyDraft",
    "StatsAvailability",
    "StatsFreshness",
    "StatsMaintenanceSummary",
    "StatsQueueAggregate",
    "StatsSnapshot",
    "StatsTelemetrySource",
    "StatsTelemetrySummary",
    "Task",
    "TaskPage",
    "TaskState",
    "TimeoutError",
    "TransportError",
    "encode_path_segment",
    "__version__",
]
