"""Public deterministic client test kit (SDK-13).

Importable from a clean ``queue-service-client-core`` wheel without server,
database, or pytest dependencies.
"""

from __future__ import annotations

from queue_service_client_testing._secrets import (
    RedactedAssertionError,
    clear_registered_secrets,
    redact_failure_text,
    register_secret,
    registered_secrets,
    safe_headers,
    safe_json,
    synthetic_bearer_token,
    synthetic_claim_token,
    synthetic_idempotency_key,
)
from queue_service_client_testing.clock import DeterministicClock
from queue_service_client_testing.fixtures import (
    auth_headers,
    capabilities,
    capabilities_body,
    claim_grant_body,
    claim_response_body,
    claim_summary_body,
    enqueue_response_body,
    idempotency_headers,
    page_body,
    task,
    task_body,
)
from queue_service_client_testing.responses import (
    cancelled_error,
    json_response,
    lease_lost_error,
    no_content,
    ok,
    protocol_error,
    timeout_error,
    uncertain_transport_error,
)
from queue_service_client_testing.scenarios import (
    RecordingHooks,
    as_steps,
    capabilities_ok,
    combine_scenarios,
    recording_instrumentation,
    scenario_cancellation,
    scenario_instrumentation_enqueue,
    scenario_lease_lost_on_complete,
    scenario_pagination,
    scenario_retry_budget,
    scenario_uncertain_enqueue,
)
from queue_service_client_testing.transport import (
    RecordedRequest,
    RequestMatcher,
    ScriptStep,
    ScriptedAsyncTransport,
    ScriptedScenario,
    ScriptedSyncTransport,
    StepOutcome,
    explain_calls,
)

__all__ = [
    "DeterministicClock",
    "RecordedRequest",
    "RecordingHooks",
    "RedactedAssertionError",
    "RequestMatcher",
    "ScriptStep",
    "ScriptedAsyncTransport",
    "ScriptedScenario",
    "ScriptedSyncTransport",
    "StepOutcome",
    "as_steps",
    "auth_headers",
    "cancelled_error",
    "capabilities",
    "capabilities_body",
    "capabilities_ok",
    "claim_grant_body",
    "claim_response_body",
    "claim_summary_body",
    "clear_registered_secrets",
    "combine_scenarios",
    "enqueue_response_body",
    "explain_calls",
    "idempotency_headers",
    "json_response",
    "lease_lost_error",
    "no_content",
    "ok",
    "page_body",
    "protocol_error",
    "recording_instrumentation",
    "redact_failure_text",
    "register_secret",
    "registered_secrets",
    "safe_headers",
    "safe_json",
    "scenario_cancellation",
    "scenario_instrumentation_enqueue",
    "scenario_lease_lost_on_complete",
    "scenario_pagination",
    "scenario_retry_budget",
    "scenario_uncertain_enqueue",
    "synthetic_bearer_token",
    "synthetic_claim_token",
    "synthetic_idempotency_key",
    "task",
    "task_body",
    "timeout_error",
    "uncertain_transport_error",
]
